volumes:
  memcached-data:
    driver: ${VOLUMES_DRIVER}

services:

### Memcached ############################################
  memcached:
    build:
      context: ${MEMCACHED_HOST_PATH}
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        MEMCACHED_VERSION: ${MEMCACHED_VERSION}
    container_name: ${MEMCACHED_CONTAINER_NAME}
    hostname: ${MEMCACHED_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      - memcached-data:/var/lib/memcached
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    environment:
      TZ: "${TZ}"
    networks:
      backend:
        ipv4_address: ${MEMCACHED_BACKEND_IP}
