ARG DOCKER_REGISTRY_URL=
ARG MYSQL_VERSION=5.7.43
FROM ${DOCKER_REGISTRY_URL}bitnami/mysql:${MYSQL_VERSION}

LABEL maintainer="zaizai <373045134@qq.com>"

ENV TZ=Asia/Shanghai

RUN mkdir -p /bitnami/mysql/secure-files
