volumes:
  mysql8-data:
    driver: ${VOLUMES_DRIVER}

secrets:
  mysql_root_password:
    file: ${MYSQL8_HOST_PATH}/mysql_root_password
  mysql_password:
    file: ${MYSQL8_HOST_PATH}/mysql_password 

services:

### Mysql8 ################################################
  mysql8:
    build:
      context: ${MYSQL8_HOST_PATH}
      args:
        MYSQL_VERSION: ${MYSQL8_VERSION}
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
    hostname: ${MYSQL8_HOSTNAME}
    container_name: ${MYSQL8_CONTAINER_NAME}
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      - "mysql8-data:/var/lib/mysql"
      - "${MYSQL8_HOST_PATH}/conf:/etc/mysql/conf.d"
      - "${MYSQL8_HOST_PATH}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "${MYSQL8_HOST_PORT}:3306"
    environment:
      TZ: "${TZ}"
      MYSQL_DATABASE: "${MYSQL8_DATABASE}"
      MYSQL_USER: "${MYSQL8_USER}"
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_INITDB_SKIP_TZINFO: "1"
    networks:
      backend:
        ipv4_address: ${MYSQL8_BACKEND_IP}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p=$(cat /run/secrets/mysql_root_password)']
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
