volumes:
  mssql-data:
    driver: ${VOLUMES_DRIVER}

services:

### MSSQL ################################################
  mssql:
    build:
      context: ${MSSQL_HOST_PATH}
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        MSSQL_VERSION: ${MSSQL_VERSION}
    hostname: ${MSSQL_HOSTNAME}
    container_name: ${MSSQL_CONTAINER_NAME}
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - "${MSSQL_HOST_PORT}:1433"
    environment:
      TZ: ${TZ}
      MSSQL_PID: ${MSSQL_PID}
      MSSQL_DATABASE: ${MSSQL_DATABASE}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
    networks:
      backend:
        ipv4_address: ${MSSQL_BACKEND_IP}
