services:

### Busybox ################################################
  busybox:
    build:
      context: ${BUSYBOX_HOST_PATH}
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        BUSYBOX_VERSION: ${BUSYBOX_VERSION}
    container_name: ${BUSYBOX_CONTAINER_NAME}
    hostname: ${BUSYBOX_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    privileged: true
    stdin_open: true
    user: root
    tty: true
    networks:
      backend:
        ipv4_address: ${BUSYBOX_BACKEND_IP}
