volumes:
  redis-stack-data:
    driver: ${VOLUMES_DRIVER}
  redis-stack-log:
    driver: ${VOLUMES_DRIVER}

x-redis-stack:
  redis-args: &redis-args "--requirepass ${REDIS_STACK_PASSWORD} --appendonly yes"

services:

### Redis Stack ##############################################
  redis-stack:
    build:
      context: ${REDIS_STACK_HOST_PATH}
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        REDIS_STACK_VERSION: ${REDIS_STACK_VERSION}
    container_name: ${REDIS_STACK_CONTAINER_NAME}
    hostname: ${REDIS_STACK_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      - redis-stack-data:/data
      - redis-stack-log:/var/log/redis
    ports:
      - "${REDIS_STACK_HOST_PORT}:6379"
      - "${REDIS_STACK_INSIGHT_PORT}:8001"
    environment:
      TZ: "${TZ}"
      REDIS_ARGS: *redis-args
    networks:
      backend:
        ipv4_address: ${REDIS_STACK_BACKEND_IP}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_STACK_PASSWORD}", "2>/dev/null", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
